config/routes.rb
Cloudmarket::Application.routes.draw do

  get "store/index"

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :users do
    resources :products
  end

  root :to => 'store#index' , :as => 'store'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :adress, :category, :highprice, :price, :quantity, :storeName, :title, :user_id, :unit, :available

  validates_presence_of :price, :quantity, :title, :unit

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :picture, :provider, :uid, :oauth_token, :oauth_expires_at, :admin

  has_many :products, :dependent => :destroy

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.picture = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def check_login
    unless authorized?
      redirect_to "/"
    end
  end

  def logged_in?
    if session[:user_id]
      return true
    else
      return false
    end
  end

  protected
  def authorized?
    logged_in? && (request.get? || current_user.admin?)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :get_user
  # :get_student is defined at the bottom of the file,
  # and takes the student_id given by the routing and
  # converts it to an @student object.


  # GET /products
  # GET /products.json
  def index
    @products = @user.products
    # was @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = @user.products.find(params[:id])
    # was @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @user = User.find(params[:user_id])
    @product = @user.products.build
    # was @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = @user.products.find(params[:id])
    #was @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = @user.products.build(params[:product])
    # was @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to user_products_url(@user), notice: 'Product was successfully created.' }
        # format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = @user.products.find(params[:id])
    # was @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to user_products_url(@user), notice: 'El producto fue creado exitosamente.' }
        # format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = @user.products.find(params[:id])
    #was @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to (user_products_path(@user)) }
      #was format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
  # get_user converts the user_id given by the routing
  # into an @student object, for use here and in the view.
  def get_user
    @user = User.find(params[:user_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to store_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to store_url
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  before_filter :get_user #encontrar un usuario solo si esa logueado


  def index
    @products = Product.all
    @users = User.all
    @product = @user.products.build(params[:product]) # para pasarselo al form de crear producto
    # was @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end
  
  def create
    @product = @user.products.build(params[:product])
    # was @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to store, notice: 'El producto fue creado.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  # get_user converts the user_id given by the routing
  # into an @user object, for use here and in the view.

  def get_user
      if current_user
        @user = User.find(current_user.id)
      else
        @user = User.find(1)
      end
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  before_filter :check_login

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<html ng-app="Cloud">
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Fabián Ríos at fabianrios.co">
    <meta name="description" content="Una comunidad para hacer mercado, comparte las cosas que compras y enterate donde puedes comprar tus productos habituales. ¿Quieres saber cuanto costo ese producto el mes pasado, o que productos consumen y donde compran los demas?">

  	<title><%= content_for?(:title) ? yield(:title) : "CloudMarket" %></title>

  	<%= stylesheet_link_tag    "application" %>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
	
	<script type='text/javascript'>
	(function (d, t) {
	  var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
	  bh.type = 'text/javascript';
	  bh.src = '//www.bugherd.com/sidebarv2.js?apikey=tbxquve5iq7b6fhxbl0x0w';
	  s.parentNode.insertBefore(bh, s);
	  })(document, 'script');
	</script>
	
  </head>

  <body ng-controller="ProductsCtrl">
    <div class="row">
      <div class="large-5 small-12 columns">
        <header>
          <h1 class="no-margin"><a href="/"><%= image_tag("logo.png") %> CloudMarket</a></h1>
          <h4 class="subheader no-margin pretitle">Una comunidad para hacer mercado.</h4>
        </header>
      </div>
      <div class="large-7 small-12 columns">
        <div class="user_nav right">
          <% if current_user %>
              <%= link_to  'Personas' ,users_path, :class => "button terciary small radius" %>
              <%= link_to  'Mi Alacena' ,user_products_path(current_user.id), :class => "button terciary small radius" %>
              <%= link_to image_tag(current_user.picture, :class => 'circle'), user_path(current_user.id) %> <strong><%= current_user.name %> </strong>
			 
              <%= link_to(signout_path, {:id => "sign_out"}) do %>
				  <span class="icon-exit"></span>
              <% end %>
			  
          <% else %>
              <%= link_to("/auth/facebook", {:id => "sign_in", :class => "button round face"}) do %>
				  <span class="icon-facebook"></span> Conectar con Facebook
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield %>
	<div class="row social-buttons">
		<div class="large-8 columns text-center large-centered small-centered">
			<!-- AddThis Button BEGIN -->
			<span class='st_facebook_large' displayText='Facebook'></span>
			<span class='st_linkedin_large' displayText='LinkedIn'></span>
			<span class='st_twitter_large' displayText='Tweet'></span>
			<span class='st_googleplus_large' displayText='Google +'></span>
			<span class='st_pinterest_large' displayText='Pinterest'></span>
		</div>
	</div>
	<br />
    <footer>
      <p class="text-center"><small>&copy; 2013 <a href="http://fabianrios.co" targe="_blank"> Fabián Ríos</a></small></p>
    </footer>
    
    <%= javascript_include_tag "application" %>

	<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
	<script type="text/javascript">stLight.options({publisher: "0f2c7b97-b311-4a36-886f-144703bd1035", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
    
  </body>
</html>

app/views/products/_form.html.erb
<% content_for :title, "Nuevo producto - cloudmarket" %>

<% categories = { 'Frutas' => 'Frutas', 'Carnes' => 'Carnes', 'Pescados' => 'Pescados', 'Granos y procesados' => 'Granos y procesados', 'Tuberculos' => 'Tuberculos', 'Hortalizas' => 'Hortalizas', 'Licores' => 'Licores', 'Aseo' => 'Aseo', 'Hogar' => 'Hogar', 'Bebes' => 'bebes', 'Mascotas' => 'Mascotas', 'Vehiculos' => 'Vehiculos', 'Lacteos' => 'Lacteos' }%>
<% unidades = { 'Kilo' => 'Kilo', 'Gramos' => 'Gramos', 'Libra' => 'Libra', 'Litro' => 'Litro', 'Docena' => 'Docena', 'Bulto' => 'Bulto', 'Arroba' => 'Arroba', 'Caja' => 'Caja', 'Atado' => 'Atado'  }%>

<%= form_for([@user, @product] , :html => {:class => 'custom-set'}) do |f| %>
    <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="large-8 columns">
        <div class="field">
          <%= f.label :title, 'Nombre:' %>
          <%= f.text_field :title %>
        </div>
        <div class="field">
          <label>Nombre del lugar:</label>
          <input type="text" ng-model="lugar" googleplace/>
        </div>
        <div class="field">
          <%= f.label :storeName, 'Nombre corto del lugar' %>
          <%= f.text_field :storeName %>
        </div>
        <%= f.text_field :adress, "ng-model" => "lugar", :class => "hide" %>
      </div>
      <div class="large-4 columns">
       <div class="row">
		   <div class="large-6 columns">
			<div class="field">
	       	  <%= f.label :price, 'Precio' %>
	       	  <%= f.text_field :price%>
		  	</div>
		</div>
		<div class="large-6 columns">
			<div class="field">
			  <%= f.label :quantity, 'Cantidad' %>
			  <%= f.number_field :quantity %>
			</div>
		</div>
       </div>
        <% if current_user && current_user.admin? %>
        <div class="field">
          <%= f.label :highprice, 'Precio promedio' %>
          <%= f.text_field :highprice %>
        </div>
        <% end %>
        <div class="field">
          <%= f.label :available, '¿Comprar?' %>
          <%= f.check_box :available %>
        </div>
        <div class="field">
          <%= f.label :category, 'Categoría' %>
          <% list = categories.sort %>
          <%= f.select :category, list %>
        </div>
        <div class="field">
          <%= f.label :unit, 'Presentación' %>
          <% lista = unidades.sort %>
          <%= f.select :unit, lista %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <div class="actions">
          <%= f.submit "Continuar", class: 'button success right' %>
        </div>
      </div>
    </div>
<% end %>

app/views/products/edit.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1 class="subheader">Editar Producto <small>en la Alacena de <%= @user.name %></small></h1>

    <%= render 'form_edit' %>

   <div class="back">
	    <%= link_to 'Volver', user_products_path(@user), :class => 'button terciary left' %>
	</div>
   </div>
</div>

app/views/products/index.html.erb
<% content_for :title, "Home - cloudmarket" %>

<div class="row">
  <div class="large-8 small-12 columns large-centered">
      <%= content_tag(:div, raw(notice+'<a href="#" class="close">&times;</a>'), class: 'alert-box success', 'data-alert' => '') if notice %>
      <%= content_tag(:div, alert,  class: 'alert-box alert', 'data-alert' => '' ) if alert  %>
    <h3 class="subheader">Alacena de <%= image_tag @user.picture, :class => 'circle' %> <%= @user.name %></h3>
    <hr>
	
    <form class="custom">
      <div class="row">
        <div class="large-9 columns">
			<input type="search" class="large" placeholder="¿Qué producto buscas?" ng-model="query">
        </div>
        <div class="large-3 columns">
          <label for="customDropdown">Orden:</label>
          <select id="customDropdown" ng-model="orderProp" class="form-control">
            <option value="title">Alfabético</option>
            <option value="category">Categoría</option>
          </select>
        </div>
      </div>
    </form>
	<hr />
	<% if current_user.id == @user.id %>
	<h3 class="text-right"><span class="graytxt"><span class="icon-signup"></span> TOTAL:</span> <span class="label radius">{{getPrice() | currency:'$' }}</span></h3>
	<% end %>
    <% if !@user.products.empty? %>
	<ul class="no-bullet listado" ui-sortable="sortableOptions" ng-model="products">
		<li ng-repeat="fridge in fridges | filter:query | orderBy:orderProp" class="{{fridge.category}}" id="{{fridge.user_id}}">
			<div class="title-info">
				<div class="row">
					<div class="large-6 columns">
						<h4>
							<span class="handle icon-list"></span> {{fridge.title}}
							<% if current_user && current_user.id == @user.id %>
							<a href="/users/{{fridge.user_id}}/products/{{fridge.id}}/edit" class="edit">
								<span class="icon-pencil"></span>
							</a>
							<a href="/users/{{fridge.user_id}}/products/{{fridge.id}}" class="delete" data-confirm="Estas seguro de querer borrarlo?" data-method="delete" rel="nofollow">
								<span class="icon-remove"></span>
							</a>
							<% end %>
						</h4>
						<% if current_user.id == @user.id %>
							<form action="#" class="custom-set" ng-show="fridge.available">
								<label for="checkbox{{$index}}"><input type="checkbox" id="checkbox{{$index}}"> Comprar</label>
							</form>
						<% end %>
					</div>
					<div class="large-6 columns">
						<div class="prices">
							<span class="market">{{fridge.price | currency:'$'}}</span>
						</div>
					</div>
				</div><!-- /row -->
			</div>
			<div class="more-info">
				<span class="left"><strong ng-bind="fridge.quantity"></strong><strong ng-bind="fridge.unit"></strong> </span> <span class="the-category {{fridge.category}}" ng-bind="fridge.category"></span>
				<div class="text-center place">
					<strong ng-bind="fridge.storeName"></strong>
					<small ng-bind="fridge.adress"></small>
				</div>
			</div>	
		</li>
	</ul>
    <% else %>
        <div data-alert class="alert-box secondary"><%= @user.name %> No has creado ningun producto.<a href="#" class="close">&times;</a></div>
    <% end %>

    <br>
    <% if current_user.id == @user.id %>
       <%= link_to 'Crear Producto', new_user_product_path(@user), :class => "button right success" %>
    <% end %>
   </div>
</div>

<% if current_user && current_user.admin? %>
<!-- <pre>{{products | json}}</pre> -->
<% end %>

app/views/products/new.html.erb
<div class="row">
  <div class="large-12 columns">
    <% if current_user.id == @user.id %>
    <h2 class="subheader">Nuevo Producto </h2>

    <%= render 'form' %>
    <% else %>

        <div data-alert class="alert-box alert">No puedes crear productos en la alacena de <%= @user.name %><a href="#" class="close">&times;</a></div>

    <% end %>
	<div class="back">
		<%= link_to 'Volver', user_products_path(@user), :class => 'button terciary left' %>
	</div>
  </div>
</div>

app/views/products/show.html.erb
<% content_for :title, "#{@product.category} - #{@product.title} - CloudMarket" %>

<div class="row">
  <div class="small-12 large-8 large-centered columns">
    <p id="notice"><%= notice %></p>

    <ul class="no-bullet listado">
      <li class="<%= @product.category %>">
        <div class="title-info">
          <h4><%= @product.title %></h4>
          <div class="prices">
            <span class="market"><%= @product.price %></span>
            <span class="supermarket"><%= @product.highprice %></span>
          </div>
        </div>
        <div class="more-info">
          <span class="left"><%= @product.quantity %> KILO</span> <span class="the-category <%= @product.category %>"><%= @product.category %></span>
          <div class="text-center place">
              <strong><%= @product.storeName %></strong>
              <small><%= @product.adress %></small>
          </div>
        </div>
      </li>
    </ul>

    <%= link_to 'Editar', edit_user_product_path(@product) %> |
    <%= link_to 'Volver', user_product_path(@user)  %>
  </div>
</div>

app/views/store/index.html.erb
<% content_for :title, "Home - cloudmarket" %>
<!-- para que coja las posibles unidades en el formulario -->
<% unidades = { 'Kilo' => 'Kilo', 'Gramos' => 'Gramos', 'Libra' => 'Libra', 'Litro' => 'Litro', 'Docena' => 'Docena', 'Bulto' => 'Bulto', 'Arroba' => 'Arroba', 'Caja' => 'Caja', 'Atado' => 'Atado'  }%>

<div class="row">
  <div class="large-8 small-12 columns large-centered">
	   

    <form class="custom">
      <input type="search" class="large" placeholder="¿Qué producto buscas?" ng-model="query">
      <div class="row">
        <div class="large-9 columns">
          <input type="search" class="large" placeholder="¿Dónde?" ng-model="lugar">
        </div>
        <div class="large-3 columns">
          <label for="customDropdown">Orden:</label>
          <select id="customDropdown" ng-model="orderProp" class="form-control">
            <option value="title">Alfabético</option>
            <option value="category">Categoría</option>
          </select>
        </div>
      </div>
    </form>

    <%= content_tag(:div, raw(notice+'<a href="#" class="close">&times;</a>'), class: 'alert-box success', 'data-alert' => '') if notice %>
    <%= content_tag(:div, alert,  class: 'alert-box alert', 'data-alert' => '' ) if alert  %>
	
	
    <ul ui-sortable="sortableOptions" ng-model="products" class="no-bullet listado" >
      <li ng-repeat="product in products | filter:query | orderBy:orderProp | filter:lugar" class="{{product.category}}">
        <div class="title-info">
          <h4> <span class="handle icon-list"></span> {{product.title}} 
			  <% if current_user && current_user.id %>
			  	<a href="#" data title="añadir a mi alacena" data-reveal-id="clone-{{$index}}"><span class="icon-copy"></span> <span class="add-word">Agregar</span> </a>
			  <% end %>
		  </h4>
          <h6 class="subheader"><small>{{ product.updated_at | date:'MMMM dd, yyyy' }}</small></h6>
          <div class="prices">
            <span class="market" ng-bind="product.price | currency:'$'"></span>
            <span class="supermarket" ng-bind="product.highprice | currency:'$'"></span>
          </div>
        </div>
        <div class="more-info">
          <span class="left">{{product.quantity}} </span> <strong ng-bind="product.unit"></strong> <span class="the-category {{product.category}}" ng-bind="product.category"></span>
          <div class="text-center place">
            <strong ng-bind-html-unsafe="product.storeName"></strong>
            <small ng-bind="product.adress"></small>
          </div>
        </div>
		<!-- modal -->
		<% if current_user %>
		<div id="clone-{{$index}}" class="reveal-modal" data-number="{{product.id}}">
			<h3 class="subheader">Guardalo en tu alacena</h3>
			<%= form_for([@user, @product] , :html => {:class => 'custom'}) do |f| %>
			    <% if @product.errors.any? %>
			        <div id="error_explanation">
			          <h2><%= pluralize(@product.errors.count, "error") %> No dejaron crear este producto:</h2>
					  <br />
			          <ul class="no-bullet">
			            <% @product.errors.full_messages.each do |msg| %>
			                <li><%= msg %></li>
			            <% end %>
			          </ul>
			        </div>
			    <% end %>
				<div class="row">
					<div class="large-9 columns">
						<div class="field">
						  <label>Nombre del lugar:<span class="redtxt">*</span></label>
						  <input type="text" ng-model="lugar" googleplace/>
						  <%= f.text_field :adress, "ng-model" => "lugar", :class => "hide" %>
						</div>
					</div>
					<div class="large-3 columns">
			  			<div class="field">
			  	       	  <%= f.label :price, raw('Precio: <span class="redtxt">*</span>') %>
			  	       	  <%= f.number_field :price, value: "{{product.price}}" %>
			  		  	</div>
					</div>
				</div>
				<hr />
				<div class="row">
					<div class="large-5 columns">
						<div class="field">
						  <%= f.label :title, raw('Nombre del producto: <span class="redtxt">*</span>') %>
						  <%= f.text_field :title, :placeholder => "Nombre del producto, ej: Tomates", value: "{{product.title}}"  %>
						</div>
					</div>
					<div class="large-3 columns">
						<div class="field">
							<%= f.label :quantity, raw('Cantidad: <span class="redtxt">*</span>') %>
							<%= f.number_field :quantity, value: "{{product.quantity}}" %>
						</div>
					</div>
					<div class="large-4 columns">
						<div class="field">
							<%= f.label :unit, raw('Presentación: <span class="redtxt">*</span>') %>
							<% lista = unidades.sort %>
							<%= f.select :unit, lista, :selected => @product.unit %>
						</div>
					</div>
				</div>
				<%= f.submit "Guardar", class: 'button success full' %>
			<% end %>
			<a class="close-reveal-modal">&#215;</a>
		</div>
		<% end %>
      </li>
    </ul>
	<div ng-show="(products | filter:query).length == 0">
		<h2 class="subheader text-center">No encontramos <strong>{{query}}</strong></h2>
		<h3 class="subheader text-center">Se el primero en 
		<% if current_user %>
			<small><%= link_to 'crear este producto', new_user_product_path(@user), :class => "button success radius text-center" %></small>
		<% else %>
			<small><%= link_to("/auth/facebook", {:id => "sign_in", :class => "button success radius text-center"}) do %>crear este producto<% end %></small>
		<% end %>
		</h3>
	</div>
	
	<div ng-show="(products | filter:lugar).length == 0">
		<h2 class="subheader text-center">No encontramos el lugar <strong>{{lugar}}</strong></h2>
		<h3 class="subheader text-center">Se el primero en 
		<% if current_user %>
			<small><%= link_to 'crear este lugar', new_user_product_path(@user), :class => "button success radius text-center" %></small>
		<% else %>
			<small><%= link_to("/auth/facebook", {:id => "sign_in", :class => "button success radius text-center"}) do %>crear este lugar<% end %></small>
		<% end %>
		</h3>
	</div>
	
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="large-12 columns">
    <% if current_user.id == @user.id || current_user.admin %>
        <h2 class="subheader">Editar usuario</h1>
        <%= render 'form' %>
    <% end %>
    <%= link_to 'Ver', @user %> |
    <%= link_to 'Volver', users_path %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="large-12 columns">
    <h3 class="subheader"><%= image_tag @user.picture, :class => 'circle' %> <%= @user.name %> <small><%= mail_to @user.email %></small></h3>


    <br />
    <% if current_user && current_user.admin? %>
        <%= link_to 'Editar', edit_user_path(@user), :class => 'button right success' %>
    <% end %>
    <%= link_to 'Volver', users_path, :class => 'button terciary' %>


  </div>
</div>